name: Main
on: push

# TODO - Need to not repeat the checkout and setup node steps...

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install standard
      - run: npm run lint